version: "3.8"
services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  # После запуска можно зайти по http://localhost:9000
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=tima@sh.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 9000:80
